DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

DROP TABLE IF EXISTS images;
CREATE TABLE images (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    img_name VARCHAR(255) NOT NULL,
    img_size BIGINT UNSIGNED NOT NULL,
    img_path VARCHAR(255) NOT NULL,
    viewed BIGINT UNSIGNED NOT NULL DEFAULT 0
);
